### PR TITLE
Support Android API29 + gradle 6

### PR DESCRIPTION
**Pull request by ralic**

### CODE REVIEW

**Comment by mvayngrib** [comment]
@ralic thanks for the PR but there are way too many unrelated changes - style, reordering lines, etc.

**Comment by mvayngrib** [comment]
actually, this looks like a duplicate of #97

**Comment by ralic** [comment]
Most clean up and line changes are actually using Microsoft VS code. Not sure if you would like to compare it with branch #97 , so that you could do a merge for both of our codes.

**Comment by mvayngrib** [comment]
@ralic do u want to update this PR with minimal changes (no style/reordering/androix changes etc)?

**Pull request closed without merging**
