### PR TITLE
Don't include examples in the npm package

### PR DESCRIPTION
**Pull request by syaau**
The npm package being published are quite big in size (around 70MB). The npm install takes quite a lot of time while installing the package because of this. The problem is the examples folder was also being included in the npm package, which are not required for the library to run. I have added a "files" section in package.json which includes only the files/folders required for the library.

### CODE REVIEW

**Comment by mvayngrib** [comment]
@syaau thanks for the PR! Totally for the idea, but I think a .npmignore file would work better. All it would need is:

```
examples/
```

otherwise we'll need to remember to update the "files" field for any new files or renames, which sounds like a pain

mind updating the PR?

**Comment by syaau** [comment]
I was also thinking the same first. But it seems .npmignore and .gitignore files do not work well together.  .gitignore is ignored if .npmignore is used. So I didn't want to use .npmignore file. Let me know if you prefer using .npmignore.

**Comment by mvayngrib** [comment]
@syaau could you clarify what you mean by them not working together? As far as I know they work as follows:

git only looks at .gitignore
npm looks at .npmignore. If .npmignore is not present, it falls back to .gitignore

**Comment by syaau** [comment]
@mvayngrib if .npmignore is present then .gitignore is ignored. Then any files that would have been ignored because of .gitignore would then not be ignored.

**Comment by mvayngrib** [comment]
@syaau ah, I see what you mean. So is we went the .npmignore route, .npmignore would have to be the same as .gitignore plus the `examples/` line

i think because this repo is unlikely to store any secrets (keys, credentials, etc.), let's go the .npmignore route. This way we risk publishing future releases with extra files (heavier), rather than with files missing (broken).

**Comment by syaau** [comment]
@mvayngrib I have updated the files.

**Comment by syaau** [comment]
@mvayngrib great library. Thanks a lot. We are using it to add a feature of playing game in local network. So far haven't faced any issue.

**Comment by mvayngrib** [comment]
@syaau thanks, send a link to the game if you like :) 

can you make .npmignore a copy of .gitignore with the *addition* of examples/ ? I just peeked in .gitignore and i see the list of files we don't want to commit/publish is actually disgustingly extensive

**Comment by syaau** [comment]
@mvayngrib Done.

**Comment by mvayngrib** [comment]
thanks, released in 2.3.0

**Pull request merged**
