### PR TITLE
initial android support

### PR DESCRIPTION
**Pull request by aprock**
moved ios specific code into a subfolder
created an android folder
updated the Install instructions on the readme
bumped the version to 0.2.0

### CODE REVIEW

**Comment by mvayngrib** [comment]
@aprock awesome! Do you think we should move the android stuff into a separate repo, and rename this one react-native-udp-ios, or keep them together?

**Comment by aprock** [comment]
my preference would be to keep them in the same repo.

**Comment by mvayngrib** [comment]
@aprock sounds good. I don't have the bandwidth at the moment to test this, so I'll leave it to you to merge (but make sure it doesn't break the iOS part). Very excited about this PR.

**Comment by aprock** [comment]
@mvayngrib fair enough. I have verified that iOS still works.  With the new subfolder the iOS instructions and XCode project needed a small revision, but other than that, there weren't any changes to it..

**Comment by urbien** [comment]
we are planning to use this on android soon, thank you Andy!

**Pull request merged**
