### PR TITLE
standard buffer

### PR DESCRIPTION
**Pull request by zwhitchcox**
This was causing problems with my usage

### CODE REVIEW

**Comment by Rapsssito** [comment]
@zwhitchcox, take a look at this [note ](https://github.com/tradle/react-native-udp#note) in the documentation, it might help you.

**Comment by zwhitchcox** [comment]
I saw that, but I guess I just don't understand why not just eliminate the problem altogether?

**Comment by Rapsssito** [comment]
@zwhitchcox, I am working on an overall dependency reduction that introduces this change. I will update this PR when it is ready.

**Comment by zwhitchcox** [comment]
Oh, ok, so shall I close this issue, or do you want me to keep it open?

**Comment by Rapsssito** [comment]
@zwhitchcox, keep the PR open for now so I can check for reference.

**Comment by Rapsssito** [comment]
Closed for #133

**Pull request closed without merging**
