### PR TITLE
hostname improvement

### PR DESCRIPTION
**Pull request by serus22**
i did one small improvement to hostname check, this fix enables you to work with ESP wifi modules for example, working hostname exaple: ESP_CC99AA (on android hotspot)

### CODE REVIEW

**Comment by serus22** [comment]
the reason is when u have udp socket on android device for example, and u receive data from this socket you can't send response because rinfo.address is e.g. ESP_CC99AA and socket.send say "invalid address"

**Comment by mvayngrib** [comment]
@serus22 thanks for the PR! It would be good to restrict this as much as possible. Is the ESP_ prefix part of some standard? If so then maybe we can match ESP_XXXXX rather than any hostname with an underscore vs a dot. I'm not familiar with hostnames like ESP_XXXXX, but happy to be educated :)

**Comment by serus22** [comment]
Yep I realize that format  it does not look not standard (ESP is Chinese WiFi iot module so :D), but its pretty annoying if you received address to which u can not answer, i will take a deeper look when i get some free time later 

i dont know hot your module works but maybe it will be better if you can put precise IP into 'rinfo' object instead of host-name, if its possible, maybe there are some OS limitations i don't know

**Comment by serus22** [comment]
this underscore was pretty annoying problem, i wont to have custom fork of this module and improving rules does not looks as a good idea, i read some articles about hostnames and i never found nothing about undersocres, so i improved my ESP device and it sends me IP first where i can send response, its maybe not very clever but working

**Comment by serus22** [comment]
https://github.com/tradle/react-native-udp/blob/master/android/src/main/java/com/tradle/react/UdpReceiverTask.java#L50

**Pull request closed without merging**
