### PR TITLE
Update react-native-udp.podspec

### PR DESCRIPTION
**Pull request by zi6xuan**
I found the bug on the iOS build `'React/RCTAssert.h' file not found`

### CODE REVIEW

**Comment by mvayngrib** [comment]
@zi6xuan is the `exclude_files` line needed?

**Comment by zi6xuan** [comment]
I did the test and didn't need `exclude_files`

**Comment by mvayngrib** [comment]
@zi6xuan cool, push without the `exclude_files` line and i'll merge

**Comment by zi6xuan** [comment]
ok

**Pull request merged**
