### PR TITLE
Fix for iOS 10

### PR DESCRIPTION
**Pull request by the-ress**
The custom shell script doesn't expect double digit SDK version numbers and detects SDK 10.0 as 0.0.

I applied the change from this fork of the original script: https://gist.github.com/raspu/0dfb442db086549a568ede6f338cbfb3

### CODE REVIEW

**Comment by skv-headless** [comment]
approve this issue. @mvayngrib please merge

**Comment by skv-headless** [comment]
Here what exactly changed https://gist.github.com/raspu/0dfb442db086549a568ede6f338cbfb3/revisions#diff-3de1199730f2c758448eaab1baa5af56R40

**Comment by mvayngrib** [comment]
LGTM! ping @aprock

**Comment by mvayngrib** [comment]
ok, confirmed problem and fix in xcode 8, sorry for the wait guys and @the-ress thanks for the PR!

**Pull request merged**
