### PR TITLE
Support React Native 0.40.x header imports

### PR DESCRIPTION
**Pull request by tohjg**

### CODE REVIEW

**Comment by mvayngrib** [comment]
@tohjg is there anything else that needs to change? Is there a minimum react-native-cli version or something else? Here's what I did:

```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.41.2
$ react-native init rctudp
$ cd rctudp
$ npm i --save tradle/react-native-udp#pull/36/head # this PR
$ react-native link react-native-udp
rnpm-install info Linking react-native-udp android dependency 
rnpm-install info Android module react-native-udp has been successfully linked 
rnpm-install info Linking react-native-udp ios dependency 
rnpm-install info iOS module react-native-udp has been successfully linked 
```

Then I built in XCode, and this is what I'm getting:

image

I also tried with cli version 1.2.0, not sure if that matters.

npm, node versions:
```
$ npm --version
3.10.3
~/Code/rctudp on master
$ node --version
v6.5.0
```

**Comment by tohjg** [comment]
@mvayngrib I found that shell script inside UdpSockets Xcode project causing 'Shell Invocation Error'. I'm not sure what's the usage. 

Anyhow, I created a virgin React Native project and testing using [react-native-ssdp](https://github.com/netbeast/react-native-ssdp) to test uPnP discovery. Successfully run on both simulator and iphone 6s.

**Comment by mvayngrib** [comment]
looks like that script was introduced in https://github.com/tradle/react-native-udp/pull/25 to combat Xcode 8, but i guess Xcode 8 has since gotten smarter.

**Comment by mvayngrib** [comment]
@tohjg released as 2.0.0, thanks!

**Pull request merged**
